version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:7
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:20
    restart: always
    working_dir: /usr/src/clean-node-api
    command: sh -c "npm install --only=prod && npm run debug" # takes more time than Dockerfile - run attached to analyze (without -d)
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
